### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by underscorephil** [softlayer/slick#3]
Add support for VSI/baremetal tagging

**Comment by mbernar** [comment]
Added some tagging functionality in creating a virtual instance and viewing the tags in the instance view

![6dfa570676a3cb9a](https://cloud.githubusercontent.com/assets/8440014/5669894/8b30f6fe-9749-11e4-9a73-bf203eabe3dd.jpg)
![16beb29fc822e194](https://cloud.githubusercontent.com/assets/8440014/5669899/8e6f2f20-9749-11e4-8827-7c1f130466ec.jpg)

**Comment by underscorephil** [comment]
addressed in pull/4
